In [11]:
import requests# Request, urlopen
import json
import pandas as pd
import datetime

In [4]:

r=requests.get("https://www.quandl.com/api/v3/datasets/WIKI/A.json?api_key=z3Bsb_-YBr-VQVNsGcNn&start_date=2018-02-18&end_date=2018-03-20")

In [15]:
rjson= r.json()['dataset']

In [16]:
r_df = pd.DataFrame(rjson['data'], columns = rjson['column_names'])

r

In [20]:
r_df.reset_index()

,index,Date,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
0,0,2018-03-20,69.77,70.070,69.4500,69.85,2355102.0,0.0,1.0,69.77,70.070,69.4500,69.85,2355102.0
1,1,2018-03-19,69.79,70.310,69.0600,69.34,2501900.0,0.0,1.0,69.79,70.310,69.0600,69.34,2501900.0
2,2,2018-03-16,69.92,70.340,69.0500,69.90,3301577.0,0.0,1.0,69.92,70.340,69.0500,69.90,3301577.0
3,3,2018-03-15,70.09,70.660,69.8700,70.18,2490222.0,0.0,1.0,70.09,70.660,69.8700,70.18,2490222.0
4,4,2018-03-14,71.07,71.160,69.6907,69.92,1825085.0,0.0,1.0,71.07,71.160,69.6907,69.92,1825085.0
5,5,2018-03-13,71.00,71.520,70.4200,70.68,1573113.0,0.0,1.0,71.00,71.520,70.4200,70.68,1573113.0
6,6,2018-03-12,71.20,71.530,70.6700,70.71,1858146.0,0.0,1.0,71.20,71.530,70.6700,70.71,1858146.0
7,7,2018-03-09,70.27,71.500,70.0000,71.13,1869878.0,0.0,1.0,70.27,71.500,70.0000,71.13,1869878.0
8,8,2018-03-08,69.72,70.270,69.1900,69.85,2365939.0,0.0,1.0,69.72,70.270,69.1900,69.85,2365939.0
9,9,2018-03-07,67.36,69.855,67.3000,69.70,3125788.0,0.0,1.0,67.36,69.855,67.3000,69.70,3125788.0
10,10,2018-03-06,67.78,68.420,67.4500,68.11,2942050.0,0.0,1.0,67.78,68.420,67.4500,68.11,2942050.0
11,11,2018-03-05,67.25,67.850,66.5100,67.55,1890858.0,0.0,1.0,67.25,67.850,66.5100,67.55,1890858.0
12,12,2018-03-02,66.82,67.680,66.6500,67.51,2057260.0,0.0,1.0,66.82,67.680,66.6500,67.51,2057260.0
13,13,2018-03-01,68.47,68.800,66.7900,67.38,2401795.0,0.0,1.0,68.47,68.800,66.7900,67.38,2401795.0
14,14,2018-02-28,69.42,70.000,68.5700,68.59,2657196.0,0.0,1.0,69.42,70.000,68.5700,68.59,2657196.0
15,15,2018-02-27,70.75,70.920,69.0000,69.00,3277061.0,0.0,1.0,70.75,70.920,69.0000,69.00,3277061.0
16,16,2018-02-26,71.00,71.210,70.0100,70.58,5422043.0,0.0,1.0,71.00,71.210,70.0100,70.58,5422043.0
17,17,2018-02-23,71.15,71.370,70.0600,70.70,3878648.0,0.0,1.0,71.15,71.370,70.0600,70.70,3878648.0
18,18,2018-02-22,71.72,71.760,70.5100,70.68,2290240.0,0.0,1.0,71.72,71.760,70.5100,70.68,2290240.0
19,19,2018-02-21,71.12,72.700,70.9700,71.25,1989132.0,0.0,1.0,71.12,72.700,70.9700,71.25,1989132.0
20,20,2018-02-20,71.50,71.850,70.7000,71.08,2577134.0,0.0,1.0,71.50,71.850,70.7000,71.08,2577134.0

In [31]:
from bokeh.plotting import figure, output_file, show
from bokeh.models import DatetimeTickFormatter

In [19]:
fig = figure(title = 'stock price', plot_width = 800, plot_height = 600, x_axis_type = "datetime", toolbar_location = "below", tools = "crosshair, pan, wheel_zoom, box_zoom, reset")

In [53]:
r_df.columns.values

array(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Ex-Dividend',
       'Split Ratio', 'Adj. Open', 'Adj. High', 'Adj. Low', 'Adj. Close',
       'Adj. Volume'], dtype=object)

In [54]:
from math import pi
fig.line(r_df['Date'], r_df['Open'],legend= 'Open', color="navy")
fig.line(r_df['Date'], r_df['Close'],legend= 'Close',color="firebrick")
fig.line(r_df['Date'], r_df['Adj. Open'],legend= 'Adj.Open', color="blue")
fig.line(r_df['Date'], r_df['Adj. Close'],legend= 'Adj.Close',color="green")
fig.xaxis.formatter=DatetimeTickFormatter(
        hours=["%Y-%B-%d"],
        days=["%Y-%B-%d"],
        months=["%Y-%B-%d"],
        years=["%Y-%B-%d"],
    )
fig.xaxis.major_label_orientation = pi/4

In [38]:
from datetime import datetime
r_df['Date']=pd.to_datetime(r_df['Date'])

In [55]:
show(fig)

In [57]:
stockdata = r_df  
stockdata['avg'] = (stockdata.Open + stockdata.Close)/2
stockdata['range'] = abs(stockdata.Close-stockdata.Open)
      #Check the up/down of the day to determin the bar color
inc = stockdata.Close > stockdata.Open
dec = stockdata.Open > stockdata.Close

In [58]:
w = 12*60*60*1000 # half day in ms

      #Render Plot
fig = figure(title = None, plot_width = 800, plot_height = 600, x_axis_type = "datetime", toolbar_location = "below", tools = "crosshair, pan, wheel_zoom, box_zoom, reset")
fig.segment(stockdata.Date, stockdata.High, stockdata.Date, stockdata.Low, color = "black")
fig.rect(stockdata.Date[inc], stockdata['avg'][inc], w, stockdata['range'][inc], fill_color = "black", line_color = "black")
fig.rect(stockdata.Date[dec], stockdata['avg'][dec], w, stockdata['range'][dec], fill_color = "red", line_color = "black")
fig.xaxis.formatter=DatetimeTickFormatter(
        hours=["%Y-%B-%d"],
        days=["%Y-%B-%d"],
        months=["%Y-%B-%d"],
        years=["%Y-%B-%d"],
    )
fig.xaxis.major_label_orientation = pi/4

In [59]:
show(fig)

In [29]:
stockdata.Date[inc]

0     2018-03-20
3     2018-03-15
7     2018-03-09
8     2018-03-08
9     2018-03-07
10    2018-03-06
11    2018-03-05
12    2018-03-02
19    2018-02-21
Name: Date, dtype: object